### ISSUE TITLE
WhatsApp clone not working

### ISSUE THREAD

**Issue by btastic** [mesibo/messenger-app-android#19]
Hello,

I just went through the tutorial, created an account kit account and after I try logging in I get "A system issue occurred. Please try again". In the debug console I see ` Invalid or missing region code (de) provided.`. I don't know if that helps, but I can't use the sample app right now.

Thanks

**Comment by mesibo** [comment]
You are possibly not entering your number correctly!  Please send us a screenshot.

**Comment by btastic** [comment]
Thanks for the quick response. However, posting a screenshot would make my mobile number publicly.

I changed some numbers, but the length and the first few numbers are unchanged:

![image](https://user-images.githubusercontent.com/6894999/53488040-76d54980-3a8d-11e9-8de0-66530dce3ced.png)

![image](https://user-images.githubusercontent.com/6894999/53488048-7c329400-3a8d-11e9-83a5-0c30cfbaf621.png)

**Comment by mesibo** [comment]
System error is an AccountKit error and occurs when ApplicationId or ClientToken is not set correctly.  In most cases, it will be fixed by correctly entering both the values. However, if you continue to have the issue, send us your configuration files where you have made changes and the screenshot of your AccountKit settings to contact@mesibo.com

Please also refer https://www.google.com/search?q=account+kit+system+issue+occurred

**Comment by btastic** [comment]
I just sent you an email. Thank you!

**Comment by btastic** [comment]
Solution was to create a new App with AccountKit.
