### ISSUE TITLE
Mesibo UI Modules

### ISSUE THREAD

**Issue by danieltigse** [mesibo/messenger-app-android#8]
I am sorry for adding issues but the tutorials are not as well-explained as I expected. My question is: For android. How Can I use Fragments with Mesibo? Or Do I have to necessarily call the Mesibo Activities with `MesiboUI.launch` or `MesiboUI.launchMessageView`? Can't I embed the chats view within a Fragment?

**Comment by mesibo** [comment]
Daniel, 

Yes, you can use `MesiboMessagingFragment` for messaging and `MesiboMessageListFragment` for message lists. Mesibo UI module documentation and sample source code are in progress but you can always email us at contact@mesibo.com or here.

MesiboMessagingFragment takes the following fragment arguments:

`peer` - String, peer address for one-to-one conversation, empty otherwise
`groupid` - long, group id for group conversation, 0 otherwise
`forwardid` - long, forward and launch;
`readonly` - boolean, hide controls 

MesiboMessageListFragment takes the following arguments:

`NewContactSelector` - int, can be one of the following values:
         0 - Message list
         1 - Contact Selector 
         2 - Forward 
         3 - Group Selector
         4 - Edit Group

'query' - String, search query

Hope it helps.

**Comment by danieltigse** [comment]
Well. I achieved my mission by using the fragment `m` it was hard to figure it out but, it's ok. Now I can check all the new conversations.
